apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: tomeksz
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1.14.2
          ports:
            - containerPort: 80
          env:
            - name: USERNAME
              valueFrom:
                secretKeyRef:
                  name: nginx-secret
                  key: username
            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  name: nginx-secret
                  key: password
            - name: APP_NAME
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: APP_NAME
            - name: APP_ENV
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: APP_ENV
            - name: WELCOME_MESSAGE
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: WELCOME_MESSAGE
          volumeMounts:
            - name: secret-volume
              mountPath: "/etc/secret"
              readOnly: true
            - name: app-config-volume
              mountPath: "/usr/share/nginx/html/index.html"
              subPath: index.html
              readOnly: true
      volumes:
        - name: secret-volume
          secret:
            secretName: nginx-secret
        - name: app-config-volume
          configMap:
            name: app-config
            items:
              - key: index.html
                path: index.html
